package JunitTests;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

import controller.UserClient;
import junit.framework.TestCase;

/**
 * The class <code>TestTaskSubmissionTest</code> contains tests for the class
 * {@link <code>TestTaskSubmission</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 11:46 09/07/17
 *
 * @author kobi
 *
 * @version $Revision$
 */
public class TestSubmitTask extends TestCase {
	private String student_id, task_id,course_id,submission_file;
	private UserClient userClient;
	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public TestSubmitTask(String name) {
		super(name);
	}

	/**
	 * Perform pre-test initialization
	 *
	 * @throws Exception
	 *
	 * @see TestCase#setUp()
	 */
	protected void setUp() throws Exception {
		super.setUp();
		// Add additional set up code here
		student_id = "student1";
		task_id = "1";
		course_id = "100";
		submission_file = "10100_student1-blabla.doc";
		userClient = new UserClient("localhost",5555);
	}
	public void testSubmissionUpload()
	{
		String arrans="";
		HashMap<String,ArrayList<String>> hm= new HashMap<String,ArrayList<String>>();
		ArrayList<String> arr = new ArrayList<String>();
		arr.add(student_id);
		arr.add(task_id);
		arr.add(course_id);
		arr.add(submission_file);
		hm.put("Submission Test", arr);
		try {
			userClient.sendToServer(hm);
			syncWithServer();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		arrans =  (String)(UserClient.ans);
		assertTrue(Boolean.valueOf(arrans));
		
		
	}
	public void syncWithServer()
	{
		synchronized(userClient)
		{
			UserClient.setFlagFalse();

			while(!userClient.isready())
			{
				try{
					userClient.wait();	
				}
				catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		}
	}
	/**
	 * Perform post-test clean up
	 *
	 * @throws Exception
	 *
	 * @see TestCase#tearDown()
	 */
	protected void tearDown() throws Exception {
		super.tearDown();
		// Add additional tear down code here
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = true
 * createTearDown = true
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = controller
 * package.sourceFolder = G9HAS/src
 * superclassType = junit.framework.TestCase
 * testCase = TestTaskSubmissionTest
 * testClassType = TestTaskSubmission
 */